# Recreate with: conda env create -f environment.yml
name: calcofi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - xarray
  - netcdf4
  - h5py
  - matplotlib
  - cartopy
  - holoviews
  - geoviews
  - plotly
  - colorcet
  - rioxarray
  - pytz
  - ipykernel
